"""empty message

Revision ID: 5e2bf06e2fcc
Revises: d93d22f2c47d
Create Date: 2019-07-04 16:44:45.798146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2bf06e2fcc'
down_revision = 'd93d22f2c47d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_info')
    op.add_column('accountinfo', sa.Column('model', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accountinfo', 'model')
    op.create_table('account_info',
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('spreadsheet', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###
